### ISSUE TITLE
Change or delete movie_db with moviedb.sql

### ISSUE THREAD

**Issue by ValentinaSukonina** [Ebyrdeu/movie_jakarta#29]
As the current version of moviedb.sql is now differ from our Entity class, will be reasonable to change or delete it.

**Comment by Ebyrdeu** [comment]
I do not believe a change is necessary; just deleting would be good. 

This is because as you said we utilize Hibernate for table creation in the database during our Docker build process. Theoretically, I could incorporate this as a build method, but it does not justify the effort since it does not offer any improvement.

**Comment by ValentinaSukonina** [comment]
Agree, it does not play any role here. Just thought the modified version could be added as txt file below everything as a small reference.
